### ISSUE TITLE
TridentZ Neo sticks are not recognized

### ISSUE THREAD

**Issue by atonkyra** [twifty/lights#5]
The RAM are detected on module load normally after PR #4 but the RGB triplet detection fails. One thing I noticed is that if I enable other AURA addresses from OpenRGB project (0x4F and 0x66) the motherboard detection code finds the memory sticks (AUDA0-E6K5-0101) but fails with RGB zones being 8 at https://github.com/twifty/lights/blob/9b7ab1693c1ce0da76bb91aad34824c1ae32fe41/aura/controller/aura-controller.c#L588

**Comment by twifty** [comment]
With the triplet not matching and then the zone_count being incorrect (after remapping the DIMMs with OpenRGB) it sounds like the wrong byte values are being read from the DIMM. Either the DIMM is on the wrong page or the offsets are incorrect (unlikely).

**Comment by atonkyra** [comment]
```
[ 7670.696157] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:488] Detected DIMM slot=1 addr=0x51, spd_type=0x0c, spd_sz=0x200
[ 7670.697545] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:488] Detected DIMM slot=3 addr=0x53, spd_type=0x0c, spd_sz=0x200
[ 7670.698943] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:488] Detected DIMM slot=5 addr=0x55, spd_type=0x0c, spd_sz=0x200
[ 7670.700372] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:488] Detected DIMM slot=7 addr=0x57, spd_type=0x0c, spd_sz=0x200
[ 7670.705024] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:503] Selecting page 1 for all DIMMs
[ 7670.706406] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:503] Selecting page 1 for all DIMMs
[ 7670.707771] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:503] Selecting page 1 for all DIMMs
[ 7670.709140] lights lights-aura: [/usr/src/lights/aura/memory/aura-memory.c:503] Selecting page 1 for all DIMMs
``` 

If you suppose zone_count = led_count in the RAM stick, then zone_count=8 is correct AFAIK.

**Comment by twifty** [comment]
I should have tested the changes before merging. The triplets for my DIMMs failed for me. Recoded to acknowledge the ACK. Try again now please.

**Comment by twifty** [comment]
Also, as far as I can tell, the NEO sticks only have 5 LEDs, the same as other Trident modules. Correct me if I'm wrong though.

**Comment by atonkyra** [comment]
Looks like my triplets are simply 0x00, 0x00, 0x00.

**Comment by twifty** [comment]
Are you able to confirm the triplet using `i2cdump` Addr 0xF0 0xF1 and 0xF2 ?

My triplets are 0x52 0x47 0x42 (ASCII letters RGB). If they really are all 0 then I'll have to decompile LightingService.exe again and see if they have changed.

**Comment by twifty** [comment]
Thinking about this. If it earlier failed because of the zone_count, then the triplet check MUST have passed at that time. There is something weird going on with the paging system on your sticks. I wonder if a delay is required between selecting the page and reading.

**Comment by atonkyra** [comment]
Oh just to clarify, it never passed it from memory detection code but motherboard code. Motherboard detection code identified the memory sticks as "CPU" zone (which later on caused explosions since the code tried to create multiple cpu nodes to sysfs)

**Comment by twifty** [comment]
Ahh, when you said motherboard above I thought it was a typo. Makes sense now. I'll dig into the new software version tomorrow. I don't know how long that'll take though.

**Comment by atonkyra** [comment]
Yeah, I'll continue investigaiton myself, thanks for looking into it, i2cdump from the ram stick (0x51)
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 23 10 0c 02 85 21 00 08 00 40 00 03 09 03 00 00    #????!.?.@.???..
10: 00 00 08 0c f8 03 00 00 6e 6e 6e 11 08 76 f0 0a    ..????..nnn??v??
20: 20 08 00 05 00 a8 1e 2b 2e 00 00 00 00 00 00 00     ?.?.??+........
30: 00 00 00 00 00 00 00 00 00 00 00 00 15 2b 16 36    ............?+?6
40: 0b 2b 0c 36 00 00 36 15 2b 0c 2c 16 2b 0c 00 00    ?+?6..6?+?,?+?..
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
70: 00 00 00 00 00 83 b5 ce 00 00 00 00 00 c2 af 7e    .....???.....??~
80: 11 11 21 01 00 00 00 00 00 00 00 00 00 00 00 00    ??!?............
90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 74 df    ..............t?
```

**Comment by atonkyra** [comment]
And 
```
-        if (aura_memory_rgb_triplet_exists(rgb)) {
+        if (aura_memory_rgb_triplet_exists(rgb) || 1) {
```

Makes the RGB controls work.

**Comment by twifty** [comment]
OpenRGB doesn't do the triplet check last time I looked. They check for a series of incrementing bytes.

Glad you got it working. At least we know the problem is with the triplets. Does it work when remapping the addresses and when addresses have already been remapped?

**Comment by twifty** [comment]
Are the `i2cdetect` dumps done before and after loading the lights modules? BTW the dump should go up to 0x7F, missing a few bytes at the end.

If, your newly mapped controllers should be at 0x71,73,75 and 76. Judging from your dmesg log, they have not been remapped at all and the code has aborted after trying to detect the first controller.

This dump
```
zenith ~ # i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- 11 -- -- 14 -- -- -- -- 19 -- 1b -- 1d -- 1f 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- 36 -- -- -- 3a 3b -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- 51 -- 53 -- 55 -- 57 -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: 70 71 72 73 74 75 -- 77  
```
Has me a little confused. 3 of your DIMMs have been remapped, and the 4th hasn't (the 0x77 address should disappear after all DIMMs have remapped). It says "OpenRGB has been ran once before this output", but OpenRGB should have remapped all. So I'm not sure if `lights` or `OpenRGB` has left the bus in a partially remapped state.

Either way, something has gone wrong while trying to remap. I'll add a few more debug messages and see if I can pinpoint the problem.

**Comment by atonkyra** [comment]
1st paste has the workflow

1. Boot system
2. run i2cdetect
3. make install for lights
4. run i2cdetect

And 2nd paste

1. Boot system
2. Run OpenRGB once, exit it
3. run i2cdetect
4. make install for lights
5. run i2cdetect

Not sure what you mean by dump missing data. Looking at it it has 00-FF? I've re-included both pages in case you need the other one.

```
zenith ~ # i2cdump -y 1 0x51; i2cset -y 1 0x37 00 00; i2cdump -y 1 0x51; i2cset -y 1 0x36 00 00
No size specified (using byte-data access)
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 23 10 0c 02 85 21 00 08 00 40 00 03 09 03 00 00    #????!.?.@.???..
10: 00 00 08 0c f8 03 00 00 6e 6e 6e 11 08 76 f0 0a    ..????..nnn??v??
20: 20 08 00 05 00 a8 1e 2b 2e 00 00 00 00 00 00 00     ?.?.??+........
30: 00 00 00 00 00 00 00 00 00 00 00 00 15 2b 16 36    ............?+?6
40: 0b 2b 0c 36 00 00 36 15 2b 0c 2c 16 2b 0c 00 00    ?+?6..6?+?,?+?..
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
70: 00 00 00 00 00 83 b5 ce 00 00 00 00 00 c2 af 7e    .....???.....??~
80: 11 11 21 01 00 00 00 00 00 00 00 00 00 00 00 00    ??!?............
90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 74 df    ..............t?
Error: Write failed
No size specified (using byte-data access)
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
40: 04 cd 00 00 00 00 00 00 00 46 34 2d 33 36 30 30    ??.......F4-3600
50: 43 31 36 2d 31 36 47 54 5a 4e 00 00 00 00 80 ce    C16-16GTZN....??
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 8e cf    ..............??
80: 0c 4a 05 20 00 00 00 00 00 a3 00 00 05 00 02 00    ?J? .....?..?.?.
90: 00 47 47 47 00 9f e6 f0 0a 20 08 00 05 00 c0 11    .GGG.???? ?.?.??
a0: 27 00 00 00 00 00 00 00 00 e6 a0 91 fa fa fa ba    '........???????
b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
f0: 01 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00    ???.............
Error: Write failed

```

**Comment by twifty** [comment]
I mean the dump from `i2cdetect`. The full range should be 0x00 to 0x7F, but it only shows up to 0x77. The addresses used by the remapped DIMMs use 0x70 to 0x70 (excluding 0x77). It's not so important here since I know exactly which addresses you should be using.

The address remapping persists across reboots. It's only reset when you do a full power cycle (off then on). So it looks like `lights` has caused the incomplete remapped state.

I've had a quick look at the code and I *think* I see the problem. It's setting the bus address to 0x80F8, failing to register the slot change, but not setting the bus address again after a fail. It's already 5:30am here, and I have to teach at 10, so it's unlikely I'll get it fixed soon. Within 24 hours for sure.

**Comment by twifty** [comment]
I see your triplet on page 1 at 0xF0 as "01 02 01". Those values are not in the array though. They may have been added since. Are you sure it was detected as all 0's? The newest commit has the debug message enabled.

**Comment by atonkyra** [comment]
Looked at it and seems that smbus_read_byte() ends up resetting the page (when verifying if the page changed). Too tired myself to figure out what is different from the logic of ee1004 but I noticed the following which might explain:

```
zenith /usr/src/lights # i2cset -y 1 0x37 00 00; i2cget -y 1 0x36; i2cget -y 1 0x51 0xf0
Error: Write failed
Error: Read failed
0x01
zenith /usr/src/lights # i2cset -y 1 0x37 00 00; i2cget -y 1 0x36 00; i2cget -y 1 0x51 0xf0
Error: Write failed
0x00
0x00
```

**Comment by twifty** [comment]
The only real difference between `lights` and `ee1004` is that `lights` uses read/write byte DATA, whereas `ee1004` uses the non-DATA variant. It could be causing a false positive when changing to page 1, especially when your DIMM doesn't ACK. I'll change that and add your triplet to the array.

I can see what needs fixing, it'll take some time to update and test.

**Comment by twifty** [comment]
A little longer than 24 hours, but I think I resolved the issue.

**Comment by atonkyra** [comment]
Tested few cold reboots and seems to work (both triplet detection and remapping) so closing this one. Thank you :)
